name    'puppet-gitlab'
version '0.0.10'
source  'https://github.com/openstack-hyper-v/puppet-gitlab'
author  'Andrew Tomaka, Steffen Roegner, Uwe Kleinmann, Matt Klich, Sebastien Badia'
license 'GPLv3'
summary 'Puppet GitLab Module'
description 'Module to install GitLab using puppet'
project_page 'https://github.com/openstack-hyper-v/puppet-gitlab/'
#dependency 'puppetlabs/mysql', '>= 0.6.1'
dependency 'puppetlabs/stdlib'
#dependency 'jfryman/nginx', '>= 0.0.2'
#dependency 'puppetlabs/ruby', '>= 0.0.2'
dependency 'openstack-hyper-v/redis', '>= 0.0.6'
#dependency 'sbadia/gitlab_requirements', '>= 0.2.0'
